# Generated by Django 5.2.4 on 2025-09-15 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Content of the message")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the message was created",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read by the receiver",
                    ),
                ),
                (
                    "edited",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been edited"
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was last edited",
                        null=True,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="User who receives the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_content",
                    models.TextField(
                        help_text="The previous content of the message before edit"
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the edit was made",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Version number of this edit (1 = original, 2 = first edit, etc.)"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        help_text="User who made the edit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message History",
                "verbose_name_plural": "Message Histories",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "-edited_at"],
                        name="messaging_m_message_a83591_idx",
                    ),
                    models.Index(
                        fields=["edited_by", "-edited_at"],
                        name="messaging_m_edited__92401a_idx",
                    ),
                ],
                "unique_together": {("message", "version")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "New Message"),
                            ("system", "System Notification"),
                        ],
                        default="message",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                (
                    "content",
                    models.TextField(help_text="Notification content/description"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the notification was created",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Message that triggered this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="messaging.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="messaging_n_user_id_c93178_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="messaging_n_is_read_2bb140_idx"
                    ),
                ],
            },
        ),
    ]
