# Generated by Django 5.2.4 on 2025-09-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="messaging.message",
            ),
        ),
    ]
